package com.aograph.chuan_air;
global java.util.List<DiscountCabin> discount_cabin;
global java.lang.String predictDay;
import com.aograph.chuan_air.Utils
import java.util.ArrayList;
import com.aograph.chuan_air.AirlinePredict
import java.util.Arrays;

rule "rule1"
    salience 1000
    no-loop
    when
        $cur:AirlinePredict(flight_type==1)
        and $preList:ArrayList(size >=1 ) from collect(AirlinePredict(dep==$cur.dep && arr==$cur.arr && fltno==$cur.fltno && flight_date<$cur.flight_date))
        and $nextList:ArrayList(size >=1 ) from collect(AirlinePredict(dep==$cur.dep && arr==$cur.arr && fltno==$cur.fltno && flight_date>$cur.flight_date))
    then
         AirlinePredict $pre=(AirlinePredict)$preList.get(0);
         AirlinePredict $next=(AirlinePredict)$nextList.get($nextList.size()-1);
         System.out.println($pre);
         System.out.println(Utils.getLowerPrice(discount_cabin,null,$cur,predictDay).doubleValue());
//         double[] arrs={$cur.getRule_predict_price(),Utils.getLowerPrice(discount_cabin,null,$cur,predictDay).doubleValue()};
//         $max_price=Arrays.stream(arrs).max().getAsDouble();
//
//         if (($cur.getOta_kzl() < $pre.getOta_kzl()-0.1) & ($cur.getOta_kzl() < $next.getOta_kzl()-0.1) & $cur.getOta_kzl() <= 7) {
//            $cur.setRule_predict_price($max_price);
//            $modelType=$cur.getModel_type()+",rule2.1a@"+$cur.getRule_predict_price();
//            $cur.setModel_type($modelType);
//         }
//         if (($cur.getOta_kzl() < $pre.getOta_kzl()-0.05) & ($cur.getOta_kzl() < $next.getOta_kzl()-0.05) & $cur.getEx_dif() > 7 & $cur.getEx_dif()<=13 & $cur.getOta_kzl() <0.5 ) {
//            $cur.setRule_predict_price($max_price);
//            $modelType=$cur.getModel_type()+",rule2.1b@"+$cur.getRule_predict_price();
//            $cur.setModel_type($modelType);
//         }
end


